# Generated by Django 5.1.2 on 2024-11-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=13, null=True)),
                ('credit', models.IntegerField(max_length=9)),
                ('crPass', models.IntegerField(max_length=10)),
                ('timeCreated', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
