# Generated by Django 5.1.2 on 2024-11-25 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pay',
            name='credit',
        ),
        migrations.AddField(
            model_name='pay',
            name='cash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pay',
            name='credit_No',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='pay',
            name='crPass',
            field=models.CharField(max_length=10),
        ),
    ]
